import { Router } from "express";
import { getDashboard, getSalesChart, getTopProducts, getSellerStats, getTopProfitProducts, getSellerDashboard, getLowStock } from "./analytics.controller.js";
import { authMiddleware } from "../../middleware/auth.middleware.js";
import { roleMiddleware } from "../../middleware/role.middleware.js";
const router = Router();
router.use(authMiddleware);
router.get("/seller-dashboard", getSellerDashboard);
router.use(roleMiddleware("ADMIN"));
router.get("/dashboard", getDashboard);
router.get("/sales-chart", getSalesChart);
router.get("/top-products", getTopProducts);
router.get("/sellers", getSellerStats);
router.get("/top-profit", getTopProfitProducts);
router.get("/low-stock", getLowStock);
export default router;
